# Generated by Django 4.0.4 on 2022-05-12 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('flavour', models.CharField(max_length=32)),
                ('cake_category', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
